# Site wide configuration

title: Edward Zhu
locale: en_US
description: Shoutout to the sidewalks that kept me off the streets.
# logo: site-logo.png
# logo: me.jpg
logo: EZ_logo.png
me: me.jpg
search: true
# url: http://zhued.github.io
url:


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Edward Zhu
  avatar: bio-photo.jpg
  email: edward.r.zhu@gmail.com
  disqus-shortname: edwardzhu
  twitter: edwardrzhu
  facebook: #username
  github: zhued
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: edwardrzhu
  instagram: #username
  flickr: #username
  tumblr: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot: 
  bing-verify:
